Web/feature/72
squad-b/work-assistant-web pull request #76
Opened 2021-09-22 10:19 UTC by YooInKeun

- 책 수정하기 기능 추가
- 코드 리팩토링, 포맷팅

2021-09-22 10:23 UTC, YooInKeun commented
코드가 엉망진창이지만 시간 되실 때 확인 한번씩 부탁드립니다~

2021-09-22 12:20 UTC, wndudqus reviewed
리뷰 몇가지 했습니다~ 확인 부탁드려요 @YooInKeun

2021-09-22 12:20 UTC, wndudqus commented on src/components/book/add/BookUpdatePopup.tsx
> +    const initializeBook = () => {
이런 식으로 함수 정의하는 스타일은 function component에서 하는데 function component에서도 useCallback등으로 메모이제이션을 해줍니다.

2021-09-22 12:20 UTC, wndudqus commented on src/components/book/add/BookUpdatePopup.tsx
> +      bookCategories: {
bookCategories state로 있을 필요가 있나요?
보통 state는 동적으로 변경되고, 그 값이 view에 그려지는 경우에 사용합니다.

2021-09-22 12:20 UTC, wndudqus commented on src/components/book/add/BookUpdatePopup.tsx
> +                <MenuItem value={'DEVELOP'}>개발</MenuItem>
DEVELOP 이 값들   모아서 map으로 돌릴 수 있으면 좋을 것 같아요!

2021-09-22 12:58 UTC, wndudqus reviewed
@YooInKeun 이부분도 확인 부탁드립니다.

2021-09-22 12:58 UTC, wndudqus commented on src/components/book/add/BookUpdatePopup.tsx
> +                <MenuItem value={'DEVELOP'}>개발</MenuItem>
```ts
type Category='DEVELOP'|'MANAGEMENT'|'MANAGEMENT'|'PLAN'|'MARKETING'|'SELF_IMPROVEMENT'|'LICENSE'|'DESIGN'|'FICTION'|'NONFICTION';
type 

const CategoryDisplayText={
  ['DEVELOP']:'개발',
  ['MANAGEMENT']:'경영',
  ['PLAN']:'계획',
//... '타입 종류': 보여질 string 
}

class BookAddPopup extends React.Component<{},{}>{
 private categoryMenus:Category[]=[
    'DEVELOP',//추가하기 원하는 메뉴
  ]

  public render(){
    return <>
   //....some code
    <Select autoFocus value={this.state.bookCategory} inputProps={{name:'book-category', id:'book-category'}} onChange={onChangeCategory}>
              {this.categoryMenus.map((category,idx)=><MenuItem value={category}>{CategoryDisplayText[category]}</MenuItem>)}
              </Select>
   //...some code
      <>
  }

}

```

2021-09-22 12:58 UTC, wndudqus commented on src/components/common/Navbar.tsx
> +    this.state = {navItems: store.getState().isAdmin ? adminNavItems.concat(normalNavItems) : normalNavItems};
이렇게 되면 Nav가 생성되어서 마운트 될 최초시점에만 업데이트가 되고 store.getState().isAdmin이 바뀔때마다 업데이트 되지는 않을 듯합니다. 이게 의도인가요?  만약 아니라면[ connect HOC](https://react.vlpt.us/redux/09-connect.html)를 이용하거나 해당 컴포넌트를 function 컴포넌트로 바꾼 후 [useSelector](https://react.vlpt.us/redux/08-optimize-useSelector.html)등을 이용하는게 더 좋아보입니다.

2021-09-22 12:58 UTC, wndudqus commented on src/components/common/Navbar.tsx
> +    this.state = {navItems: store.getState().isAdmin ? adminNavItems.concat(normalNavItems) : normalNavItems};
@YooInKeun

2021-09-22 12:58 UTC, wndudqus commented on src/store.js
> +    let memberId;
switch case 문을 이용해서 action.type에 따른 state 변화를 시켜줘야 할 것 같아요.
이렇게 사용하는 방식은 처음봐서 혹시 참고한 코드 있다면 링크 부탁드립니다.
@YooInKeun

2021-09-22 12:59 UTC, wndudqus commented on src/components/book/detail/BookDetail.tsx
> +      if (!this.state.book.imageUrl) {
👍 @YooInKeun

2021-09-22 13:02 UTC, wndudqus requested changes

2021-09-22 13:02 UTC, wndudqus commented on src/components/book/add/BookUpdatePopup.tsx
> +      bookCategory: String,
String,Number, 이부분 아마 타입 정의 해주시려고 하신 것  같은데, 앞이 대문자인 String,Number는 타입이 아니라 JS 내장 객체입니다. 그리고 this.state에서는 값 초기화만 가능합니다.
```ts
this.state={//이부분은 타입 정의가 아니라 값 초기화만 가능.
   bookCategory:
}
```

아마 인근지능님이 하고싶으셨던 타입 정의는 따로 interface로 타입을 정의하고 아래처럼 제네릭으로 넘겨주시면 됩니다!
ex)
```ts
interface BookAddPopupState{
    bookCategory: string,
    stockQuantity:number,
    bookCategories:object,
}

class BookAddPopup extends React.Component<any,BookAddPopupState> {
//... some code
}
```

2021-09-22 13:05 UTC, wndudqus requested changes

2021-09-22 13:05 UTC, wndudqus commented on src/components/book/add/BookUpdatePopup.tsx
> +      const bookCategory = e.target.value;
render 안에서 const func=()=>{
  
} 
함수로 함수를 정의할경우 계속해서 함수가 생성돼서 성능에 좋지 못한 영향을 줍니다.
BookUpdatePopup class의 메서드로 구현하고[ constructor에서 this를 바인딩](https://ko.reactjs.org/docs/handling-events.html) 해주는 것이 더 일반적인 구현 방식입니다.

```tsx

  constructor(){
   this.onChangeCategory=this.onChangeCategory.bind(this)// 메서드로 정의한  함수는 this가 호출되는 방식에 따라 동적으로 바뀌기 때문에 함수표현식으로 정의한 함수 직접 파인딩을 명시적으로 해줘야 한다.
  }

 private onChangeCategory(){// render 함수 밖에서 메서드로 정의
      const bookCategory = e.target.value
      this.setState({bookCategory : bookCategory})
  }

 public render() {
    const {open, book, onClose} = this.props;
    return (
    <div>.....some code</div>
    )
 }
```

2021-09-26 03:45 UTC, YooInKeun commented
@wndudqus 확인이 늦었네요 주영님 🙇‍♂️, 리뷰 해주셔서 감사드립니다 👍 👍
리뷰 확인해보겠습니다~!

2021-09-26 05:20 UTC, YooInKeun commented on src/components/book/add/BookUpdatePopup.tsx
> +    const initializeBook = () => {
그렇군요 👍  function component와 useCallback을 공부해보도록 하겠습니다!

2021-09-26 05:20 UTC, YooInKeun commented on src/components/book/add/BookUpdatePopup.tsx
> +      this.setState({bookCategory: bookCategory});
꿀팁 감사합니다

2021-09-26 05:23 UTC, wndudqus commented on src/components/book/add/BookUpdatePopup.tsx
> +    const initializeBook = () => {
https://github.com/squad-b/work-assistant-web/pull/76#discussion_r713920579 이 리뷰 내용과 연결됩니다! 이 내용도 확인 부탁드립니다!
@YooInKeun

2021-09-26 05:28 UTC, YooInKeun commented on src/components/book/add/BookUpdatePopup.tsx
> +                <MenuItem value={'DEVELOP'}>개발</MenuItem>
이렇게 하는 방법이 있군요 👍 
제안주신 방법대로 수정해보겠습니다!

2021-09-26 05:47 UTC, YooInKeun commented on src/components/book/add/BookUpdatePopup.tsx
> +      const bookCategory = e.target.value;
헉 그렇군요.. 😨 
수정해야할 부분이 굉장히 많이 보이네요
좋은 피드백 감사합니다 💯

2021-09-26 05:48 UTC, YooInKeun commented on src/components/book/add/BookUpdatePopup.tsx
> +      bookCategories: {
state로 있을 필요가 없을 거 같습니다~ state에서 제외시키겠습니다!

2021-09-26 05:50 UTC, YooInKeun commented on src/components/common/Navbar.tsx
> +    this.state = {navItems: store.getState().isAdmin ? adminNavItems.concat(normalNavItems) : normalNavItems};
아니요 ㅎㅎ..  단순히 store에 정의한 state를 사용하기 위함이었습니다
connect HOC, useSelector에 대해 공부해보겠습니다 👍

2021-09-26 05:56 UTC, YooInKeun commented on src/store.js
> +    let memberId;
레퍼런스를 보고 한 건 아니고 순수하게 제 머릿속에서 작성된 것입니다.. ㅎ
궁금한 건 action.type 값 뿐만 아니라 현재 여러 조건(state, memberId, memberType)이 있는데 switch case 문을 사용해 깔끔하게 작성하는 방법이 있나요~?

2021-09-26 05:56 UTC, YooInKeun commented on src/components/book/detail/BookDetail.tsx
> +      if (!this.state.book.imageUrl) {
🙇‍♂️

2021-09-26 05:58 UTC, YooInKeun commented on src/components/book/add/BookUpdatePopup.tsx
> +      bookCategory: String,
제가 하고 싶었던 부분을 정확히 캐치하셨습니다..! 👏👏 
알려주신 방법으로 수정해보겠습니다!

2021-09-26 06:03 UTC, wndudqus commented on src/components/book/add/BookUpdatePopup.tsx
> +                <MenuItem value={'DEVELOP'}>개발</MenuItem>
redux의 store는 전역 상태를 관리하기 위한 공간이라서 store는 상태만 두는 것이 좋을 것 같습니다!

model 폴더를 하나 만들어서 그 안에 Category 파일 만들고 Category, CategoryDisplayText 등을 export해서 사용하면 좋을 것 같습니다!

2021-09-26 07:21 UTC, wndudqus commented on src/store.js
> +    if (state === undefined) {
@YooInKeun 이부분 같은 경우는 initalState를 위한 부분 같은데, 밖에서 정의하고


```ts
 memberId = JSON.parse(localStorage.getItem('memberId'));
      memberType = JSON.parse(localStorage.getItem('memberType'));
      isAdmin = memberId && memberType === 'ADMIN';

       const initState={
        memberId: memberId,
        memberType: memberType,
        isAdmin: isAdmin,
      };
createStore((state=initState, action) => {
//some code
})
```
이런 식으로 하면 조금 더 깔끔 해질 것 같습니다!

2021-09-26 07:26 UTC, wndudqus commented on src/store.js
> +    let memberId;
action.type 별로 내부에서 state, memberId, memberType 분기를 태우는게 좋아보입니다!, 다시 확인해보니 reducer 밖에서 처리하는 것이 좋아보이는 부분들이 있는 것 같아서 해당 부분들만 밖으로 빼면 깔끔해 질 것 같아 보입니다!

2021-09-26 07:26 UTC, wndudqus commented on src/store.js
> +      localStorage.setItem('memberId', JSON.stringify(memberId));
이런 side effect들은 reducer 밖에서 처리하는 것이 좋아보입니다
https://redux.js.org/understanding/thinking-in-redux/three-principles

2021-09-28 15:04 UTC, merged